### ISSUE TITLE
Split GP/JSD

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/dash-directus#42]
After https://github.com/jsdelivr/meta/issues/50, we'll need to split this into two repos.

**Comment by alexey-yarmosh** [comment]
`sponsors` collection is required by both jsd and gp.

jsd:
- `user_type: member | sponsor | special` field

gp:
- assign credits for recurring sponsorship (last assign date should be tracked)
- `user_type: member | sponsor | special` field (is it required by gp?)
  
`user_type` field is set by:
- github sponsorship webhook handler
- cron sync of `sponsors` with github every day
- user sign-up handler (searchs users in `sponsors` table)

My suggestion is to keep `sponsors` on gp dashboard as is. And jsd dashboard will not store `sponsors` explicitly, but only sync `user_type`s of the users directly with github, which shouldn't be a lot in terms of requests (once per day + on every sign-up). That assumes that jsd dashboard don't need data like amount of donation etc.

Alternatively jsd dashboard may make sync calls to gp dashboard or vice-versa. Also jsd FE may make calls to gp dashboard BE to get `user_type` value. But that has its own drawbacks and looks messy.

**Comment by MartinKolarik** [comment]
Eventually, we'll likely split even the GitHub organizations, and that means splitting sponsors (actually a good question @jimaek, shouldn't we do this sooner rather than later?). For now, keep everything GP needs there, and for JSD, either only keep the type or just ignore it (we won't be deploying the JSD dashboard until GP is done).

**Comment by jimaek** [comment]
JSD has no sponsors related functionality at all. And its not needed either. So just move everything needed to GP and dont bother with it on JSD side.

Splitting orgs sounds like a bit too much at the moment, the site already requires lots of work.
